return {
	-- 'rebelot/kanagawa.nvim',
	-- name = 'kanagawa',
	-- priority = 1000, -- Same priority as your Catppuccin
	-- config = function()
	-- 	require('kanagawa').setup({
	-- 		compile = false,
	-- 		undercurl = true,
	--
	-- 		functionStyle = {},
	-- 		statementStyle = { bold = true },
	-- 		typeStyle = {},
	--
	-- 		transparent = true,
	-- 		dimInactive = false,
	-- 		terminalColors = true,
	-- 		colors = {
	-- 			palette = {},
	-- 			theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
	-- 		},
	--
	-- 		overrides = function(colors)
	-- 			local theme = colors.theme
	-- 			return {
	-- 				LineNr = { fg = theme.ui.fg, bg = 'none' }, -- Uses main text color, 'none' for transparent bg
	-- 				-- Add any other overrides here
	-- 			}
	-- 		end,
	-- 		theme = "wave",
	-- 		background = {
	-- 			dark = "wave",
	-- 			light = "lotus"
	-- 		},
	-- 	})
	-- end,
}
