return {
	-- 'rose-pine/neovim',
	-- name = 'rose-pine',
	-- config = function()
	--   require('rose-pine').setup {
	--     variant = 'main',
	--     extend_background_behind_borders = true,
	--     enable = {
	--       terminal = true,
	--       legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
	--       migrations = true, -- Handle deprecated options automatically
	--     },
	--
	--     styles = {
	--       bold = true,
	--       italic = true,
	--       transparency = true,
	--     },
	--   }
	--   vim.cmd 'colorscheme rose-pine'
	-- end,
}
